[tool.ruff]
# Target Python 3.9
target-version = "py39"

# Set line length
line-length = 100

# Enable various rule sets
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C90",  # mccabe complexity
    "UP",   # pyupgrade
    "S",    # bandit
]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
    "S101",  # Use of assert detected (used in tests)
    "S105",  # Hardcoded password (we know about these)
    "S106",  # Hardcoded password (we know about these)
]

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info",
]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101"]  # Allow assert in tests
"config.py" = ["S105", "S106"]  # Allow hardcoded credentials in config

[tool.ruff.mccabe]
# Maximum complexity
max-complexity = 15